---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stylishm/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm install --production=false
    - npm run build
    - touch tmp/restart.txt
